//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Dentail = new HashSet<Order_Dentail>();
        }
    
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> staff_if { get; set; }
        public Nullable<double> price_total { get; set; }
        public string tick { get; set; }
        public string IsType { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Dentail> Order_Dentail { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
