//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Dentail = new HashSet<Order_Dentail>();
        }
    
        public int id_product { get; set; }
        public string name_product { get; set; }
        public double price { get; set; }
        public string introduce_product { get; set; }
        public Nullable<int> id_catogory { get; set; }
        public Nullable<int> num { get; set; }
        public string Images { get; set; }
    
        public virtual Catogory Catogory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Dentail> Order_Dentail { get; set; }
    }
}
